// Lockstep version bump for the Iris monorepo. Sets every packages/* package to
// the target version AND rewrites internal @irisrun/* dependency ranges to ^<target>,
// so the 24 publishable packages resolve each other and the git tag (vX.Y.Z) stays
// in sync with the published npm version. The release workflow enforces that the tag
// matches packages/cli/package.json — this script is how you keep them in step.
//
//   node scripts/version.mjs 0.1.1      (or: npm run version:set -- 0.1.1)
//   git commit -am "release: v0.1.1" && git tag v0.1.1 && git push --follow-tags
//
// dist/ is regenerated by the publish build, so it is not touched here.
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const version = process.argv[2];
if (!/^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$/.test(version ?? "")) {
  console.error("usage: node scripts/version.mjs <semver>   e.g. 0.1.1 or 0.2.0-rc.1");
  process.exit(1);
}

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const pkgsDir = join(root, "packages");
const DEP_FIELDS = ["dependencies", "devDependencies", "peerDependencies", "optionalDependencies"];

let changed = 0;
for (const dir of readdirSync(pkgsDir)) {
  const path = join(pkgsDir, dir, "package.json");
  let pkg;
  try {
    pkg = JSON.parse(readFileSync(path, "utf8"));
  } catch {
    continue; // not a package dir
  }
  pkg.version = version;
  for (const field of DEP_FIELDS) {
    const deps = pkg[field];
    if (!deps) continue;
    for (const name of Object.keys(deps)) {
      if (name.startsWith("@irisrun/")) deps[name] = `^${version}`;
    }
  }
  writeFileSync(path, JSON.stringify(pkg, null, 2) + "\n");
  changed++;
}

// The CLI bakes a pinned `IRIS_VERSION` constant into generated Dockerfiles /
// FaaS package.json install lines (packages/cli/src/deploy-targets.ts). A unit
// test guards it against the cli package version, so it MUST move with the bump —
// otherwise the next release fails CI on the no-drift guard. Rewrite it here so
// the constant can never go stale behind a version bump again.
const deployTargets = join(pkgsDir, "cli", "src", "deploy-targets.ts");
const IRIS_VERSION_RE = /export const IRIS_VERSION = "[^"]*";/;
try {
  const before = readFileSync(deployTargets, "utf8");
  if (!IRIS_VERSION_RE.test(before)) {
    console.error(`version: WARNING — IRIS_VERSION constant not found in ${deployTargets} (drift guard will fail)`);
  } else {
    const after = before.replace(IRIS_VERSION_RE, `export const IRIS_VERSION = "${version}";`);
    if (after !== before) writeFileSync(deployTargets, after);
    console.log(`version: set IRIS_VERSION constant → ${version} (packages/cli/src/deploy-targets.ts)`);
  }
} catch {
  console.error(`version: WARNING — could not read ${deployTargets} to update IRIS_VERSION`);
}

console.log(`version: set ${changed} packages → ${version} (internal @irisrun/* ranges → ^${version})`);
console.log(`next:\n  git commit -am "release: v${version}"\n  git tag v${version}\n  git push --follow-tags   # the release workflow builds, tests, and publishes`);
